# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slinky/abci/v1/vote_extensions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slinky/abci/v1/vote_extensions.proto',
  package='slinky.abci.v1',
  syntax='proto3',
  serialized_options=b'Z(github.com/skip-mev/slinky/abci/ve/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$slinky/abci/v1/vote_extensions.proto\x12\x0eslinky.abci.v1\"\x85\x01\n\x13OracleVoteExtension\x12?\n\x06prices\x18\x01 \x03(\x0b\x32/.slinky.abci.v1.OracleVoteExtension.PricesEntry\x1a-\n\x0bPricesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x42*Z(github.com/skip-mev/slinky/abci/ve/typesb\x06proto3'
)




_ORACLEVOTEEXTENSION_PRICESENTRY = _descriptor.Descriptor(
  name='PricesEntry',
  full_name='slinky.abci.v1.OracleVoteExtension.PricesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='slinky.abci.v1.OracleVoteExtension.PricesEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='slinky.abci.v1.OracleVoteExtension.PricesEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=190,
)

_ORACLEVOTEEXTENSION = _descriptor.Descriptor(
  name='OracleVoteExtension',
  full_name='slinky.abci.v1.OracleVoteExtension',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prices', full_name='slinky.abci.v1.OracleVoteExtension.prices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ORACLEVOTEEXTENSION_PRICESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=190,
)

_ORACLEVOTEEXTENSION_PRICESENTRY.containing_type = _ORACLEVOTEEXTENSION
_ORACLEVOTEEXTENSION.fields_by_name['prices'].message_type = _ORACLEVOTEEXTENSION_PRICESENTRY
DESCRIPTOR.message_types_by_name['OracleVoteExtension'] = _ORACLEVOTEEXTENSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OracleVoteExtension = _reflection.GeneratedProtocolMessageType('OracleVoteExtension', (_message.Message,), {

  'PricesEntry' : _reflection.GeneratedProtocolMessageType('PricesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ORACLEVOTEEXTENSION_PRICESENTRY,
    '__module__' : 'slinky.abci.v1.vote_extensions_pb2'
    # @@protoc_insertion_point(class_scope:slinky.abci.v1.OracleVoteExtension.PricesEntry)
    })
  ,
  'DESCRIPTOR' : _ORACLEVOTEEXTENSION,
  '__module__' : 'slinky.abci.v1.vote_extensions_pb2'
  # @@protoc_insertion_point(class_scope:slinky.abci.v1.OracleVoteExtension)
  })
_sym_db.RegisterMessage(OracleVoteExtension)
_sym_db.RegisterMessage(OracleVoteExtension.PricesEntry)


DESCRIPTOR._options = None
_ORACLEVOTEEXTENSION_PRICESENTRY._options = None
# @@protoc_insertion_point(module_scope)
