# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cometbft.types.v1 import validator_pb2 as cometbft_dot_types_dot_v1_dot_validator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='types.proto',
  package='cometbft.abci.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btypes.proto\x12\x10\x63ometbft.abci.v1\x1a!cometbft/types/v1/validator.proto\"V\n\x12\x45xtendedCommitInfo\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x31\n\x05votes\x18\x02 \x03(\x0b\x32\".cometbft.abci.v1.ExtendedVoteInfo\"r\n\x08VoteInfo\x12/\n\tvalidator\x18\x01 \x01(\x0b\x32\x1c.cometbft.types.v1.Validator\x12\x35\n\rblock_id_flag\x18\x03 \x01(\x0e\x32\x1e.cometbft.types.v1.BlockIDFlag\"\xaf\x01\n\x10\x45xtendedVoteInfo\x12/\n\tvalidator\x18\x01 \x01(\x0b\x32\x1c.cometbft.types.v1.Validator\x12\x16\n\x0evote_extension\x18\x03 \x01(\x0c\x12\x1b\n\x13\x65xtension_signature\x18\x04 \x01(\x0c\x12\x35\n\rblock_id_flag\x18\x05 \x01(\x0e\x32\x1e.cometbft.types.v1.BlockIDFlagb\x06proto3'
  ,
  dependencies=[cometbft_dot_types_dot_v1_dot_validator__pb2.DESCRIPTOR,])




_EXTENDEDCOMMITINFO = _descriptor.Descriptor(
  name='ExtendedCommitInfo',
  full_name='cometbft.abci.v1.ExtendedCommitInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='round', full_name='cometbft.abci.v1.ExtendedCommitInfo.round', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='votes', full_name='cometbft.abci.v1.ExtendedCommitInfo.votes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=154,
)


_VOTEINFO = _descriptor.Descriptor(
  name='VoteInfo',
  full_name='cometbft.abci.v1.VoteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='validator', full_name='cometbft.abci.v1.VoteInfo.validator', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_id_flag', full_name='cometbft.abci.v1.VoteInfo.block_id_flag', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=270,
)


_EXTENDEDVOTEINFO = _descriptor.Descriptor(
  name='ExtendedVoteInfo',
  full_name='cometbft.abci.v1.ExtendedVoteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='validator', full_name='cometbft.abci.v1.ExtendedVoteInfo.validator', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vote_extension', full_name='cometbft.abci.v1.ExtendedVoteInfo.vote_extension', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extension_signature', full_name='cometbft.abci.v1.ExtendedVoteInfo.extension_signature', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_id_flag', full_name='cometbft.abci.v1.ExtendedVoteInfo.block_id_flag', index=3,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=448,
)

_EXTENDEDCOMMITINFO.fields_by_name['votes'].message_type = _EXTENDEDVOTEINFO
_VOTEINFO.fields_by_name['validator'].message_type = cometbft_dot_types_dot_v1_dot_validator__pb2._VALIDATOR
_VOTEINFO.fields_by_name['block_id_flag'].enum_type = cometbft_dot_types_dot_v1_dot_validator__pb2._BLOCKIDFLAG
_EXTENDEDVOTEINFO.fields_by_name['validator'].message_type = cometbft_dot_types_dot_v1_dot_validator__pb2._VALIDATOR
_EXTENDEDVOTEINFO.fields_by_name['block_id_flag'].enum_type = cometbft_dot_types_dot_v1_dot_validator__pb2._BLOCKIDFLAG
DESCRIPTOR.message_types_by_name['ExtendedCommitInfo'] = _EXTENDEDCOMMITINFO
DESCRIPTOR.message_types_by_name['VoteInfo'] = _VOTEINFO
DESCRIPTOR.message_types_by_name['ExtendedVoteInfo'] = _EXTENDEDVOTEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtendedCommitInfo = _reflection.GeneratedProtocolMessageType('ExtendedCommitInfo', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDEDCOMMITINFO,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.abci.v1.ExtendedCommitInfo)
  })
_sym_db.RegisterMessage(ExtendedCommitInfo)

VoteInfo = _reflection.GeneratedProtocolMessageType('VoteInfo', (_message.Message,), {
  'DESCRIPTOR' : _VOTEINFO,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.abci.v1.VoteInfo)
  })
_sym_db.RegisterMessage(VoteInfo)

ExtendedVoteInfo = _reflection.GeneratedProtocolMessageType('ExtendedVoteInfo', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDEDVOTEINFO,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.abci.v1.ExtendedVoteInfo)
  })
_sym_db.RegisterMessage(ExtendedVoteInfo)


# @@protoc_insertion_point(module_scope)
